version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - errorlint
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - noctx
    - gocritic
    - revive
    - misspell
    - unconvert
    - prealloc
  
  settings:
    errcheck:
      check-type-assertions: true
    revive:
      rules:
        - name: exported
        - name: error-strings
        - name: error-return

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/KKKHEAO/rest_booking